### ISSUE TITLE
Change the project name

### ISSUE THREAD

**Issue by roukmoute** [flug/System#3]
Here is a proposal: StrongType

http://en.wikipedia.org/wiki/Strong_and_weak_typing

**Comment by flug** [comment]
Why use the namespace "System"? Simply to standardize all the language. Certe each language to its peculiarities, but I think that the standardization is the key to quickly learn a language.

View that PHP is relatively backward on typing, it makes sense I think that's what classes based on existing systems such as C # or Java. 
String in C # is in the namespace "System". 
String in Java is in the namespace "java.lang"
And finally as the characters are related to the system, that is why my choice is the namespace System
